// <auto-generated />
using LivestockTracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LivestockTracker.Database.Migrations
{
    [DbContext(typeof(LivestockContext))]
    partial class LivestockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("LivestockTracker.Models.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ArrivalWeight");

                    b.Property<int>("BatchNumber");

                    b.Property<DateTime>("BirthDate");

                    b.Property<DateTime?>("DateOfDeath");

                    b.Property<bool>("Deceased");

                    b.Property<int>("Number");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchasePrice");

                    b.Property<DateTime?>("SellDate");

                    b.Property<decimal?>("SellPrice");

                    b.Property<bool>("Sold");

                    b.Property<string>("Subspecies")
                        .HasMaxLength(50);

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("LivestockTracker.Models.MedecineType", b =>
                {
                    b.Property<int>("TypeCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("ID");

                    b.HasKey("TypeCode");

                    b.ToTable("Medecine");
                });

            modelBuilder.Entity("LivestockTracker.Models.MedicalTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnimalID");

                    b.Property<decimal>("Dose");

                    b.Property<int>("MedecineTypeCode");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("Unit");

                    b.HasKey("ID");

                    b.HasIndex("AnimalID");

                    b.ToTable("MedicalTransactions");
                });

            modelBuilder.Entity("LivestockTracker.Models.Unit", b =>
                {
                    b.Property<int>("TypeCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("ID");

                    b.HasKey("TypeCode");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("LivestockTracker.Models.MedicalTransaction", b =>
                {
                    b.HasOne("LivestockTracker.Models.Animal", "AnimalObject")
                        .WithMany("MedicalTransactions")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
