<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <ItemGroup>
    <ProjectReference Include="..\livestock-tracker\livestock-tracker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ecd421b8-b203-4eb9-916b-98c283cc2b94</UserSecretsId>
  </PropertyGroup>

</Project>
