// <auto-generated />
using System;
using LivestockTracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LivestockTracker.Database.Migrations
{
    [DbContext(typeof(SqliteLivestockContext))]
    [Migration("20200426123719_CleanArchitecture")]
    partial class CleanArchitecture
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("LivestockTracker.Database.Models.AnimalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ArrivalWeight")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateOfDeath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deceased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SellDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subspecies")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Animals","animal");
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.FeedTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeedTypes","feed");
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.FeedingTransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnName("AnimalID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedTypeId")
                        .HasColumnName("FeedTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnName("UnitID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("FeedTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("FeedingTransactions","feed");
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.MedicalTransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnName("AnimalID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicineId")
                        .HasColumnName("MedicineID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnName("UnitID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("UnitId");

                    b.ToTable("MedicalTransactions","medical");
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.MedicineTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedicineTypes","medical");
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.UnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units","dbo");
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.FeedingTransactionModel", b =>
                {
                    b.HasOne("LivestockTracker.Database.Models.AnimalModel", "Animal")
                        .WithMany("FeedingTransactions")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivestockTracker.Database.Models.FeedTypeModel", "FeedType")
                        .WithMany("FeedingTransactions")
                        .HasForeignKey("FeedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivestockTracker.Database.Models.UnitModel", "UnitOfMeasurement")
                        .WithMany("FeedingTransactions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivestockTracker.Database.Models.MedicalTransactionModel", b =>
                {
                    b.HasOne("LivestockTracker.Database.Models.AnimalModel", "Animal")
                        .WithMany("MedicalTransactions")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivestockTracker.Database.Models.MedicineTypeModel", "Medicine")
                        .WithMany("MedicalTransactions")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivestockTracker.Database.Models.UnitModel", "UnitOfMeasurement")
                        .WithMany("MedicalTransactions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
