name: Angular

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/**.md"
      - "**/.gitignore"
      - "**/.gitattributes"
      - "**/.vs/**"
      - "**/.vscode/**"
      - "scripts/**"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./src/livestock-tracker/ClientApp/package-lock.json
      - name: Install packages
        run: npm ci
        working-directory: ./src/livestock-tracker/ClientApp
      - name: Lint
        run: npm run lint --if-present
        working-directory: ./src/livestock-tracker/ClientApp
      - name: Build Angular
        run: npm run build
        working-directory: ./src/livestock-tracker/ClientApp
