name: e2e tests

on:
  push:
    branches:
      - master
      - e2e-*
    paths-ignore:
      - src/**/*.stories.ts
      - src/**/*.stories.spec.ts
      - test/**/*.cs
      - docs
      - docs-project
      - scripts

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run test
          working-directory: ./test/e2e
